### ISSUE TITLE
Crashes when on server selection screen

### ISSUE THREAD

**Issue by Talyda** [BisectStudios/BisectHostingServerIntegrationMenu#11] opened 2023-10-16 20:44 UTC
Hiya! When I have this mod enabled, I am _very_ frequently crashing to desktop when I am on the server selection screen. Doesn't happen all the time, but since I disabled the mod, it has not happened at all!

Crash log below
https://gist.github.com/Talyda/e5c64c6285086688b4706f6810482db0

**Comment by Quarris** [comment] 2023-10-31 19:19
Hey, could you let me know more about what modpack or modlist you might be using? Also do you remember at what point exactly did this happen? For example when opening the screen, or clicking a button? This information would be really helpful, thank you 😊

**Comment by Talyda** [comment] 2023-10-31 20:40
Sure!
Modpack is the Minecolonies Raid event modpack: https://legacy.curseforge.com/minecraft/modpacks/official-minecolonies-special-events/files/4754472
When it happened was usually when clicking the button to join the server.
Things that might be my imagination - sometimes it seems like if I don't move the mouse after clicking that button I can get through. But that might be my imagination as it doesn't actually crash EVERY time I try to join =)

And just for good measure, here's a new crash log, that happened just then when I was checking when happened so I got you the right information ;) (I forgot to turn the mod off again when the pack updated =P)
https://gist.github.com/Talyda/b1316a8f42af778665c64e519485e75d

**Comment by ghost** [comment] 2024-09-14 13:41
This seems to be the exact same crash I was about to report so lemme provide some details,

Talyda has probably been accidently clicking the button next to the join button that is suppose to rearrange server entries.

BHMenu is accidently showing this button even where there isn't a server above to swap the server with.

E.g. This is how the server list looks without modifications in AOE's Craftoria modpack:
![image](https://github.com/user-attachments/assets/9b6a04f5-0431-4fbf-b96a-f26e831214ad)

And this is how it looks when BHMenu is installed:
![image](https://github.com/user-attachments/assets/dffc038f-fc69-4772-b5bb-f04c4111f283)

_Notice the erroneous up arrow._
And another crash report from NeoForge though I suspect this affects all versions of the mod: https://api.mclo.gs/1/raw/UsYNHXF

**Comment by ghost** [comment] 2024-09-14 16:47
Sorry for the ping but I've necro'd an old issue and at least from my perspective it's hard to tell if anyone would be notified otherwise: @BisectStudios @GabrielOlvH

**Comment by SHXRKIEgg** [comment] 2024-09-26 18:01
I am able to reproduce this issue just with the Bisect Mod installed.
[crash-2024-09-27_01.54.53-client.txt](https://github.com/user-attachments/files/17153647/crash-2024-09-27_01.54.53-client.txt)

In the image below, if you select a certain area of the server join button it crashes
![image](https://github.com/user-attachments/assets/4cec0a10-7da1-463b-b9bd-b4af62dbc336)

**Comment by BisectStudios** [comment] 2024-09-26 19:29
We are investigating the issue currently.

**Comment by GabrielOlvH** [comment] 2024-09-27 16:28
Thank you all the info, this issue has been resolved in all forge affected versions (1.15+) and you can find the new updates in CurseForge and Modrinth! (some might take longer to approve because a lot of files were uploaded)

**Closed as completed by GabrielOlvH** 2024-09-27 16:28 UTC
