### ISSUE TITLE
Cannot see friends servers in Essential mod when using this mod.

### ISSUE THREAD

**Issue by Jetpack-Cat** [BisectStudios/BisectHostingServerIntegrationMenu#5] opened 2022-08-29 06:59 UTC
![2022-08-28_23 35 15](https://user-images.githubusercontent.com/100042170/187141698-591ec105-1fc1-40c6-bb86-c1aad4a9d35a.png)
I also reported this to the Essential Devs. When using this mod and the Essential mod for 1.16.5 Forge, this mod hides the essential mod friends servers.

It would be preferred if bisect could move the banner to the bottom where it doesn't interfere. If there was a way for me to move it with fancy menu I would just fix it myself, but the bisect mod doesn't allow me to do anything to it with fancy menu.

**Comment by Quarris** [comment] 2022-08-29 13:05
Hmm, the issue isnt strictly with the positioning of the banner itself. I'll try to see what I can do to make them interact

**Comment by Quarris** [comment] 2022-08-30 12:42
Could you link the Curseforge page for the Essentials mod?

**Comment by Jetpack-Cat** [comment] 2022-08-30 12:54
https://www.curseforge.com/minecraft/mc-mods/essential-mod

**Comment by DJtheRedstoner** [comment] 2022-09-11 18:29
@Quarris Hi! Essential Developer here. Please create a ticket (`#support`) in [our discord](https://discord.gg/essential) then tag me (`DJtheRedstoner#6408`) so we can work together to solve this.

**Comment by BisectStudios** [comment] 2023-07-07 10:32
We are actively working on a fix for this!

**Comment by BisectStudios** [comment] 2023-09-07 22:20
@DJtheRedstoner @Jetpack-Cat We have just released update V2.4.1 to Modrinth and Curseforge improving compatibility with Essentials and other menu-altering mods! Let us know if you encounter any issues :)

**Closed as completed by BisectStudios** 2023-09-07 22:20 UTC
Labels: bug
